name: Run Checks

on:
  pull_request:
    branches:
      - main

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18.16.0
        uses: actions/setup-node@v3
        with:
          node-version: "18.16.0"

      #  When a cache is created by a workflow run triggered on a pull request, the cache is created for the merge ref (refs/pull/.../merge). Because of this, the cache will have a limited scope and can only be restored by re-runs of the pull request.
      # - name: Get node_modules cache
      #   uses: actions/cache@v3
      #   id: node_modules
      #   env:
      #     cache-name: node-modules
      #   with:
      #     path: |
      #       **/node_modules
      #     key: ${{ runner.os }}-18.16.0-${{ env.cache-name }}-main-${{ hashFiles('**/yarn.lock') }}

      - run: yarn install

      - name: Prettier Fix
        run: yarn prettier:fix

      - name: Prettier check
        run: yarn prettier:check

      - name: Lint Fix
        run: yarn lint:fix

      - name: Lint check
        run: yarn lint:check

      - name: Typescript errors
        run: yarn typecheck
