name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.16.0"

      #  Workflow runs also cannot restore caches created for different tag names.
      # - name: Get node_modules cache
      #   uses: actions/cache@v3
      #   id: node_modules
      #   env:
      #     cache-name: node-modules
      #   with:
      #     path: |
      #       **/node_modules
      #     key: ${{ runner.os }}-18.16.0-${{ env.cache-name }}-main-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn add semantic-release @semantic-release/changelog @semantic-release/commit-analyzer @semantic-release/git @semantic-release/release-notes-generator @semantic-release/github
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PAT }}
        run: npx semantic-release
